// Registers the offline service worker once, and lets the UI know whether it worked.
// It only exists in production builds (generated by vite.config.ts). The relative
// URL makes it work under any GitHub Pages repository path.

let registration: Promise<ServiceWorkerRegistration> | null = null

export function registerServiceWorker(): Promise<ServiceWorkerRegistration> | null {
  if (registration || !import.meta.env.PROD || !('serviceWorker' in navigator)) return registration
  registration = new Promise<void>((resolve) => {
    if (document.readyState === 'complete') resolve()
    else window.addEventListener('load', () => resolve(), { once: true })
  }).then(() => navigator.serviceWorker.register('./sw.js'))
  // Offline support is a bonus; the app works without it.
  registration.catch(() => undefined)
  return registration
}

export function serviceWorkerRegistration(): Promise<ServiceWorkerRegistration> | null {
  return registration
}
